import{a as q,S as v,i}from"./assets/vendor-f736e62a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function h(r,o){return(await q.get("https://pixabay.com/api/",{params:{key:"43225364-5b24397dc6bdfd6f28f380de9",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const M=document.querySelector(".gallery"),$=new v(".gallery a",{captionsData:"alt"});function f(r){const o=r.map(({largeImageURL:a,webformatURL:c,tags:e,likes:t,views:s,comments:w,downloads:P})=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${a}">
        <img class="photo" src="${c}" alt="${e}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${s}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${w}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${P}</p></li>
        </ul>
        </li>`).join("");M.insertAdjacentHTML("beforeend",o),$.refresh()}const m=document.querySelector(".loader"),g=document.querySelector(".form"),x=document.querySelector("#text"),u=document.querySelector(".btn"),y=document.querySelector(".gallery");function L(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}function O(){u.classList.remove("is-hidden")}function p(){u.classList.add("is-hidden")}let l,n=1,b=0;const R=15;g.addEventListener("submit",I);async function I(r){if(r.preventDefault(),p(),L(),y.innerHTML="",n=1,l=x.value.trim(),!l){i.show({message:"Please complete the field!",position:"topRight"}),d();return}try{const o=await h(l,n);b=Math.ceil(o.totalHits/R),o.hits.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(f(o.hits),S())}catch{i.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}d(),g.reset()}u.addEventListener("click",B);async function B(){n+=1,p(),L();try{const r=await h(l,n);f(r.hits)}catch{i.error({message:"Sorry, an error occurred while loading. Please try again!",position:"topRight"})}d(),C(),S()}function S(){n>=b?(p(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):O()}function C(){const r=y.firstChild.getBoundingClientRect().height;scrollBy({top:r,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
