import{S as u,i as a}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function m(s){const r=new URLSearchParams({key:"43225364-5b24397dc6bdfd6f28f380de9",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${r}`).then(o=>o.json())}const f=document.querySelector(".gallery"),h=new u(".gallery a",{captionsData:"alt"});function d(s){const r=s.map(({largeImageURL:o,webformatURL:i,tags:e,likes:t,views:n,comments:l,downloads:p})=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${o}">
        <img class="photo" src="${i}" alt="${e}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${n}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${l}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${p}</p></li>
        </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r),h.refresh()}const y=document.querySelector(".form"),g=document.querySelector("#text"),b=document.querySelector(".gallery"),c=document.querySelector(".loader");y.addEventListener("submit",L);function L(s){s.preventDefault(),b.innerHTML="";const r=g.value.trim();c.classList.remove("is-hidden"),r===""&&a.warning({color:"yellow",message:"Please full in the field for serch",position:"topRight"}),m(r).then(o=>{o.hits.length===0&&a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"}),d(o.hits),s.target.reset()}).catch(o=>{console.log(o),a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>c.classList.add("is-hidden"))}
//# sourceMappingURL=commonHelpers.js.map
